---
- name: Backup Ansible Automation Platform
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - vars/aap_common.yml

  vars:
    backup_date: "{{ ansible_date_time.iso8601_basic_short }}"

  tasks:
    - name: Run AAP backup
      include_tasks: tasks/backup_aap.yml
